name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
      - name: Lint
        run: composer lint
      - uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-
