name: Lint
on: [push]
jobs:
  wporg-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: pantheon-systems/action-wporg-validator@1.0.0
        with:
          type: plugin
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
      - name: Lint
        run: composer lint
      - uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-
          paths: ${{ github.workspace }}/wp-progress-bar.php ${{ github.workspace }}/wppb-widget.php ${{ github.workspace }}/functions.php
