name: Scan for Vulnerabilities
on: [push, pull_request]
jobs:
  vuln:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
    steps:
      - uses: actions/checkout@v3
      - name: Start MariaDB
        run: |
          sudo systemctl start mysql
      - name: Install Extras
        run: |
          sudo apt-get update
          sudo apt-get install subversion
      - name: Install WordPress Test Suite
        run: |
          echo "Installing WP Test Suite so we can use it for vulnerability scanning..."
          bash bin/install-wp-tests.sh wppb_tests root root 127.0.0.1 latest
      - name: Install WP-CLI
        run: |
          echo "Installing WP-CLI..."
          cd /tmp/wordpress
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
      - name: Set up WordPress
        run: |
          echo "Setting up WordPress..."
          cd /tmp/wordpress
          wp config create --dbname=wppb_tests --dbuser=root --dbpass=root --dbhost=127.0.0.1
          wp core install --url=wordpressprogressbar.test --title=WordPress --admin_user=progressbar --admin_password=password --admin_email=noreply@dev.null
      - name: Set up plugins & vulnerability scanner
        run: |
          echo "Setting up plugins & vulnerability scanner..."
          cd /tmp/wordpress
          echo "GITHUB_WORKSPACE"
          ls -la ${GITHUB_WORKSPACE}
          mkdir wp-content/plugins/progress-bar
          cp -r ${GITHUB_WORKSPACE}/* wp-content/plugins/progress-bar
          echo "Plugins directory"
          ls -la wp-content/plugins
          ls -la wp-content/plugins/progress-bar
          wp plugin activate progress-bar
          wp plugin delete hello
          wp plugin delete akismet
          rm wp-content/db.php
          wp plugin list
          wp package install 10up/wpcli-vulnerability-scanner:dev-trunk
          wp config set VULN_API_PROVIDER wordfence
          wp config set VULN_API_TOKEN ''
      - name: Scan for vulnerabilities
        run: |
          cd /tmp/wordpress
          if [[ $(wp vuln plugin-status) =~ "No vulnerabilities reported for this version of progress-bar" ]]; then
            echo "✨ No vulnerabilities found"
            exit 0
          else
            echo "❌ Vulnerabilities found"
            exit 1
          fi
